export const languages = [
    "JavaScript",
    "Python",
    "Java",
    "Embedded",
    "C#",
    "C++",
    "SQL",
    "TypeScript",
    "Ruby",
    "Swift",
    "HTML",
    "CSS",
    "Kotlin",
    "PHP",
    "Golang",
    "Perl"
]

export const software = [
    "Unity",
    "Azure",
    "AWS",
    "Google Cloud",
    "Power BI",
    "Tableau",
    "Photoshop",
    "Illustrator",
    "SharePoint",
    "Microsoft Dynamics",
    "VMware",
    "Oracle",
    "Figma",
    "Terraform",
    "Puppet",
    "GCP",
    "Microsoft Excel"
]

export const frameworks = [
    "React",
    "Angular",
    "Vue",
    "Redux",
    "Spring",
    ".NET",
    "Spark",
    "Hadoop",
    "Django",
    "PyTorch",
    "SciKit",
    "TensorFlow",
    "BigQuery",
    "Kafka",
    "ElasticSearch",
    "Flask"
]

export const other = [
    "Artificial intelligence",
    "Machine learning",
    "CI/CD",
    "Linux",
    "REST",
    "GraphQL",
    "Oracle",
    "NoSQL",
    "MySQL",
    "Docker",
    "Kubernetes",
    "Databases",
    "UX",
    "SEO",
    "CRO",
    "DevOps",
    "Virtual reality",
    "Blockchain",
    "Scrum",
    "Cybersecurity",
    "Big data",
    "Unix",
    "Data science",
    "MongoDB",
    "PostgreSQL",
    "Bash",
    "Shell",
    "Powershell",
    "Node",
    "Git"
]